name: Deploy to Railway

on: 
  push:
    branches:
      - main
  # This is a dummy change to trigger a new deployment
  workflow_dispatch:

env:
  RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Railway
        run: | 
          curl -fsSL https://railway.app/install.sh | bash
          railway login

      - name: Deploy to Railway
        run: railway up --service backend --project $RAILWAY_PROJECT_ID
